# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Clisso < Formula
  desc ""
  homepage ""
  version "0.16.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/allcloud-io/clisso/releases/download/0.16.2/clisso_darwin_amd64.zip"
      sha256 "6e1faa1317077648e2d7f303b45926bde5aa0b2462ebda7984e57961c8841ece"

      def install
        bin.install "clisso"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/allcloud-io/clisso/releases/download/0.16.2/clisso_darwin_arm64.zip"
      sha256 "9f4eaa6198db363c7b75282d6caaa5062e378e4d13c4c8345bd2874d3324aaac"

      def install
        bin.install "clisso"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/allcloud-io/clisso/releases/download/0.16.2/clisso_linux_amd64.zip"
      sha256 "81c1a05d238e8d8ff387306ae1244da12794cc2971911409c7bfddc516b99715"

      def install
        bin.install "clisso"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/allcloud-io/clisso/releases/download/0.16.2/clisso_linux_arm64.zip"
      sha256 "ea289432c47710657738eb0488d10f18866f4e70e39ece5b3eac9650810f71fe"

      def install
        bin.install "clisso"
      end
    end
  end
end
